version: '3'

services:

  # https://docs.rundeck.com/docs/administration/configuration/docker.html
  rundeck:
    image: ghcr.io/mjmcconnell/rundeck:latest
    links:
      - postgres
    env_file: .env
    environment:
      RUNDECK_DATABASE_DRIVER: org.postgresql.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: rundeck
      RUNDECK_DATABASE_URL: jdbc:postgresql://postgres:5432/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      RUNDECK_GRAILS_URL: http://localhost:4440
      RD_URL: http://localhost:4440
    ports:
      - 4440:4440
    volumes:
      - ./rundeck/config/jaas-loginmodule.conf:/home/rundeck/server/config/jaas-loginmodule.conf
      - ./rundeck/config/log4j2.properties:/home/rundeck/server/config/log4j2.properties
      - ./rundeck/config/realm.properties:/home/rundeck/server/config/realm.properties
      - ./rundeck/config/ssl.properties:/home/rundeck/server/config/ssl.properties

  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_DB=rundeck
      - POSTGRES_USER=rundeck
      - POSTGRES_PASSWORD=rundeck
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
