FROM rundeck/rundeck:4.8.0

MAINTAINER NAME mjmcconnell.dev@gmail.com

LABEL name="Rundeck" \
      maintainer="mjmcconnell.dev@gmail.com" \
      version="0.1.0" \
      release="0.1.0" \
      summary="Rundeck" \
      description="Custom rundeck image used for the playground"

ARG user=1001

USER 0

# Install packages here

USER ${user}
